//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BeatmapTool.DataAccess
{
    #region 上下文
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    public partial class dbEntities : ObjectContext
    {
        #region 构造函数
    
        /// <summary>
        /// 请使用应用程序配置文件的“dbEntities”部分中的连接字符串初始化新 dbEntities 对象。
        /// </summary>
        public dbEntities() : base("name=dbEntities", "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 dbEntities 对象。
        /// </summary>
        public dbEntities(string connectionString) : base(connectionString, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// 初始化新的 dbEntities 对象。
        /// </summary>
        public dbEntities(EntityConnection connection) : base(connection, "dbEntities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region 分部方法
    
        partial void OnContextCreated();
    
        #endregion
    
        #region ObjectSet 属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Beatmap> Beatmap
        {
            get
            {
                if ((_Beatmap == null))
                {
                    _Beatmap = base.CreateObjectSet<Beatmap>("Beatmap");
                }
                return _Beatmap;
            }
        }
        private ObjectSet<Beatmap> _Beatmap;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<BeatmapSet> BeatmapSet
        {
            get
            {
                if ((_BeatmapSet == null))
                {
                    _BeatmapSet = base.CreateObjectSet<BeatmapSet>("BeatmapSet");
                }
                return _BeatmapSet;
            }
        }
        private ObjectSet<BeatmapSet> _BeatmapSet;
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        public ObjectSet<Setting> Setting
        {
            get
            {
                if ((_Setting == null))
                {
                    _Setting = base.CreateObjectSet<Setting>("Setting");
                }
                return _Setting;
            }
        }
        private ObjectSet<Setting> _Setting;

        #endregion
        #region AddTo 方法
    
        /// <summary>
        /// 用于向 Beatmap EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBeatmap(Beatmap beatmap)
        {
            base.AddObject("Beatmap", beatmap);
        }
    
        /// <summary>
        /// 用于向 BeatmapSet EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToBeatmapSet(BeatmapSet beatmapSet)
        {
            base.AddObject("BeatmapSet", beatmapSet);
        }
    
        /// <summary>
        /// 用于向 Setting EntitySet 添加新对象的方法，已弃用。请考虑改用关联的 ObjectSet&lt;T&gt; 属性的 .Add 方法。
        /// </summary>
        public void AddToSetting(Setting setting)
        {
            base.AddObject("Setting", setting);
        }

        #endregion
    }
    

    #endregion
    
    #region 实体
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="Beatmap")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Beatmap : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Beatmap 对象。
        /// </summary>
        /// <param name="id">id 属性的初始值。</param>
        public static Beatmap CreateBeatmap(global::System.Int64 id)
        {
            Beatmap beatmap = new Beatmap();
            beatmap.id = id;
            return beatmap;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 id
        {
            get
            {
                return _id;
            }
            set
            {
                if (_id != value)
                {
                    OnidChanging(value);
                    ReportPropertyChanging("id");
                    _id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("id");
                    OnidChanged();
                }
            }
        }
        private global::System.Int64 _id;
        partial void OnidChanging(global::System.Int64 value);
        partial void OnidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sid
        {
            get
            {
                return _Sid;
            }
            set
            {
                OnSidChanging(value);
                ReportPropertyChanging("Sid");
                _Sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sid");
                OnSidChanged();
            }
        }
        private Nullable<global::System.Int32> _Sid;
        partial void OnSidChanging(Nullable<global::System.Int32> value);
        partial void OnSidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Hash
        {
            get
            {
                return _Hash;
            }
            set
            {
                OnHashChanging(value);
                ReportPropertyChanging("Hash");
                _Hash = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Hash");
                OnHashChanged();
            }
        }
        private global::System.String _Hash;
        partial void OnHashChanging(global::System.String value);
        partial void OnHashChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Difficulty
        {
            get
            {
                return _Difficulty;
            }
            set
            {
                OnDifficultyChanging(value);
                ReportPropertyChanging("Difficulty");
                _Difficulty = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Difficulty");
                OnDifficultyChanged();
            }
        }
        private global::System.String _Difficulty;
        partial void OnDifficultyChanging(global::System.String value);
        partial void OnDifficultyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Background
        {
            get
            {
                return _Background;
            }
            set
            {
                OnBackgroundChanging(value);
                ReportPropertyChanging("Background");
                _Background = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Background");
                OnBackgroundChanged();
            }
        }
        private global::System.String _Background;
        partial void OnBackgroundChanging(global::System.String value);
        partial void OnBackgroundChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Audio
        {
            get
            {
                return _Audio;
            }
            set
            {
                OnAudioChanging(value);
                ReportPropertyChanging("Audio");
                _Audio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Audio");
                OnAudioChanged();
            }
        }
        private global::System.String _Audio;
        partial void OnAudioChanging(global::System.String value);
        partial void OnAudioChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> AudioLeadIn
        {
            get
            {
                return _AudioLeadIn;
            }
            set
            {
                OnAudioLeadInChanging(value);
                ReportPropertyChanging("AudioLeadIn");
                _AudioLeadIn = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("AudioLeadIn");
                OnAudioLeadInChanged();
            }
        }
        private Nullable<global::System.Int32> _AudioLeadIn;
        partial void OnAudioLeadInChanging(Nullable<global::System.Int32> value);
        partial void OnAudioLeadInChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> PreviewTime
        {
            get
            {
                return _PreviewTime;
            }
            set
            {
                OnPreviewTimeChanging(value);
                ReportPropertyChanging("PreviewTime");
                _PreviewTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("PreviewTime");
                OnPreviewTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _PreviewTime;
        partial void OnPreviewTimeChanging(Nullable<global::System.Int32> value);
        partial void OnPreviewTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Mode
        {
            get
            {
                return _Mode;
            }
            set
            {
                OnModeChanging(value);
                ReportPropertyChanging("Mode");
                _Mode = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Mode");
                OnModeChanged();
            }
        }
        private Nullable<global::System.Int32> _Mode;
        partial void OnModeChanging(Nullable<global::System.Int32> value);
        partial void OnModeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> HPDrainRate
        {
            get
            {
                return _HPDrainRate;
            }
            set
            {
                OnHPDrainRateChanging(value);
                ReportPropertyChanging("HPDrainRate");
                _HPDrainRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("HPDrainRate");
                OnHPDrainRateChanged();
            }
        }
        private Nullable<global::System.Int32> _HPDrainRate;
        partial void OnHPDrainRateChanging(Nullable<global::System.Int32> value);
        partial void OnHPDrainRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CircleSize
        {
            get
            {
                return _CircleSize;
            }
            set
            {
                OnCircleSizeChanging(value);
                ReportPropertyChanging("CircleSize");
                _CircleSize = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CircleSize");
                OnCircleSizeChanged();
            }
        }
        private Nullable<global::System.Int32> _CircleSize;
        partial void OnCircleSizeChanging(Nullable<global::System.Int32> value);
        partial void OnCircleSizeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> OverallDifficulty
        {
            get
            {
                return _OverallDifficulty;
            }
            set
            {
                OnOverallDifficultyChanging(value);
                ReportPropertyChanging("OverallDifficulty");
                _OverallDifficulty = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("OverallDifficulty");
                OnOverallDifficultyChanged();
            }
        }
        private Nullable<global::System.Int32> _OverallDifficulty;
        partial void OnOverallDifficultyChanging(Nullable<global::System.Int32> value);
        partial void OnOverallDifficultyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> ApproachRate
        {
            get
            {
                return _ApproachRate;
            }
            set
            {
                OnApproachRateChanging(value);
                ReportPropertyChanging("ApproachRate");
                _ApproachRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("ApproachRate");
                OnApproachRateChanged();
            }
        }
        private Nullable<global::System.Int32> _ApproachRate;
        partial void OnApproachRateChanging(Nullable<global::System.Int32> value);
        partial void OnApproachRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SliderMultiplier
        {
            get
            {
                return _SliderMultiplier;
            }
            set
            {
                OnSliderMultiplierChanging(value);
                ReportPropertyChanging("SliderMultiplier");
                _SliderMultiplier = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SliderMultiplier");
                OnSliderMultiplierChanged();
            }
        }
        private Nullable<global::System.Double> _SliderMultiplier;
        partial void OnSliderMultiplierChanging(Nullable<global::System.Double> value);
        partial void OnSliderMultiplierChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> NodeCount
        {
            get
            {
                return _NodeCount;
            }
            set
            {
                OnNodeCountChanging(value);
                ReportPropertyChanging("NodeCount");
                _NodeCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("NodeCount");
                OnNodeCountChanged();
            }
        }
        private Nullable<global::System.Int32> _NodeCount;
        partial void OnNodeCountChanging(Nullable<global::System.Int32> value);
        partial void OnNodeCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SliderCount
        {
            get
            {
                return _SliderCount;
            }
            set
            {
                OnSliderCountChanging(value);
                ReportPropertyChanging("SliderCount");
                _SliderCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SliderCount");
                OnSliderCountChanged();
            }
        }
        private Nullable<global::System.Int32> _SliderCount;
        partial void OnSliderCountChanging(Nullable<global::System.Int32> value);
        partial void OnSliderCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> SpinnerCount
        {
            get
            {
                return _SpinnerCount;
            }
            set
            {
                OnSpinnerCountChanging(value);
                ReportPropertyChanging("SpinnerCount");
                _SpinnerCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SpinnerCount");
                OnSpinnerCountChanged();
            }
        }
        private Nullable<global::System.Int32> _SpinnerCount;
        partial void OnSpinnerCountChanging(Nullable<global::System.Int32> value);
        partial void OnSpinnerCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> MaxCombo
        {
            get
            {
                return _MaxCombo;
            }
            set
            {
                OnMaxComboChanging(value);
                ReportPropertyChanging("MaxCombo");
                _MaxCombo = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("MaxCombo");
                OnMaxComboChanged();
            }
        }
        private Nullable<global::System.Int32> _MaxCombo;
        partial void OnMaxComboChanging(Nullable<global::System.Int32> value);
        partial void OnMaxComboChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DrainingTime
        {
            get
            {
                return _DrainingTime;
            }
            set
            {
                OnDrainingTimeChanging(value);
                ReportPropertyChanging("DrainingTime");
                _DrainingTime = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DrainingTime");
                OnDrainingTimeChanged();
            }
        }
        private Nullable<global::System.Int32> _DrainingTime;
        partial void OnDrainingTimeChanging(Nullable<global::System.Int32> value);
        partial void OnDrainingTimeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Ops
        {
            get
            {
                return _Ops;
            }
            set
            {
                OnOpsChanging(value);
                ReportPropertyChanging("Ops");
                _Ops = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Ops");
                OnOpsChanged();
            }
        }
        private Nullable<global::System.Double> _Ops;
        partial void OnOpsChanging(Nullable<global::System.Double> value);
        partial void OnOpsChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> Bpm
        {
            get
            {
                return _Bpm;
            }
            set
            {
                OnBpmChanging(value);
                ReportPropertyChanging("Bpm");
                _Bpm = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bpm");
                OnBpmChanged();
            }
        }
        private Nullable<global::System.Double> _Bpm;
        partial void OnBpmChanging(Nullable<global::System.Double> value);
        partial void OnBpmChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Double> SliderTickRate
        {
            get
            {
                return _SliderTickRate;
            }
            set
            {
                OnSliderTickRateChanging(value);
                ReportPropertyChanging("SliderTickRate");
                _SliderTickRate = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("SliderTickRate");
                OnSliderTickRateChanged();
            }
        }
        private Nullable<global::System.Double> _SliderTickRate;
        partial void OnSliderTickRateChanging(Nullable<global::System.Double> value);
        partial void OnSliderTickRateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Bid
        {
            get
            {
                return _Bid;
            }
            set
            {
                OnBidChanging(value);
                ReportPropertyChanging("Bid");
                _Bid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Bid");
                OnBidChanged();
            }
        }
        private Nullable<global::System.Int32> _Bid;
        partial void OnBidChanging(Nullable<global::System.Int32> value);
        partial void OnBidChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="BeatmapSet")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class BeatmapSet : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 BeatmapSet 对象。
        /// </summary>
        /// <param name="id">Id 属性的初始值。</param>
        public static BeatmapSet CreateBeatmapSet(global::System.Int64 id)
        {
            BeatmapSet beatmapSet = new BeatmapSet();
            beatmapSet.Id = id;
            return beatmapSet;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Int64 Id
        {
            get
            {
                return _Id;
            }
            set
            {
                if (_Id != value)
                {
                    OnIdChanging(value);
                    ReportPropertyChanging("Id");
                    _Id = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("Id");
                    OnIdChanged();
                }
            }
        }
        private global::System.Int64 _Id;
        partial void OnIdChanging(global::System.Int64 value);
        partial void OnIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Sid
        {
            get
            {
                return _Sid;
            }
            set
            {
                OnSidChanging(value);
                ReportPropertyChanging("Sid");
                _Sid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Sid");
                OnSidChanged();
            }
        }
        private Nullable<global::System.Int32> _Sid;
        partial void OnSidChanging(Nullable<global::System.Int32> value);
        partial void OnSidChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Title
        {
            get
            {
                return _Title;
            }
            set
            {
                OnTitleChanging(value);
                ReportPropertyChanging("Title");
                _Title = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Title");
                OnTitleChanged();
            }
        }
        private global::System.String _Title;
        partial void OnTitleChanging(global::System.String value);
        partial void OnTitleChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Creator
        {
            get
            {
                return _Creator;
            }
            set
            {
                OnCreatorChanging(value);
                ReportPropertyChanging("Creator");
                _Creator = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Creator");
                OnCreatorChanged();
            }
        }
        private global::System.String _Creator;
        partial void OnCreatorChanging(global::System.String value);
        partial void OnCreatorChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Artist
        {
            get
            {
                return _Artist;
            }
            set
            {
                OnArtistChanging(value);
                ReportPropertyChanging("Artist");
                _Artist = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Artist");
                OnArtistChanged();
            }
        }
        private global::System.String _Artist;
        partial void OnArtistChanging(global::System.String value);
        partial void OnArtistChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Source
        {
            get
            {
                return _Source;
            }
            set
            {
                OnSourceChanging(value);
                ReportPropertyChanging("Source");
                _Source = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Source");
                OnSourceChanged();
            }
        }
        private global::System.String _Source;
        partial void OnSourceChanging(global::System.String value);
        partial void OnSourceChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> CreatorId
        {
            get
            {
                return _CreatorId;
            }
            set
            {
                OnCreatorIdChanging(value);
                ReportPropertyChanging("CreatorId");
                _CreatorId = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CreatorId");
                OnCreatorIdChanged();
            }
        }
        private Nullable<global::System.Int32> _CreatorId;
        partial void OnCreatorIdChanging(Nullable<global::System.Int32> value);
        partial void OnCreatorIdChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.DateTime> Date
        {
            get
            {
                return _Date;
            }
            set
            {
                OnDateChanging(value);
                ReportPropertyChanging("Date");
                _Date = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Date");
                OnDateChanged();
            }
        }
        private Nullable<global::System.DateTime> _Date;
        partial void OnDateChanging(Nullable<global::System.DateTime> value);
        partial void OnDateChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Pack
        {
            get
            {
                return _Pack;
            }
            set
            {
                OnPackChanging(value);
                ReportPropertyChanging("Pack");
                _Pack = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Pack");
                OnPackChanged();
            }
        }
        private global::System.String _Pack;
        partial void OnPackChanging(global::System.String value);
        partial void OnPackChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Type
        {
            get
            {
                return _Type;
            }
            set
            {
                OnTypeChanging(value);
                ReportPropertyChanging("Type");
                _Type = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Type");
                OnTypeChanged();
            }
        }
        private Nullable<global::System.Int32> _Type;
        partial void OnTypeChanging(Nullable<global::System.Int32> value);
        partial void OnTypeChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Lang
        {
            get
            {
                return _Lang;
            }
            set
            {
                OnLangChanging(value);
                ReportPropertyChanging("Lang");
                _Lang = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Lang");
                OnLangChanged();
            }
        }
        private Nullable<global::System.Int32> _Lang;
        partial void OnLangChanging(Nullable<global::System.Int32> value);
        partial void OnLangChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Genre
        {
            get
            {
                return _Genre;
            }
            set
            {
                OnGenreChanging(value);
                ReportPropertyChanging("Genre");
                _Genre = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Genre");
                OnGenreChanged();
            }
        }
        private Nullable<global::System.Int32> _Genre;
        partial void OnGenreChanging(Nullable<global::System.Int32> value);
        partial void OnGenreChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Video
        {
            get
            {
                return _Video;
            }
            set
            {
                OnVideoChanging(value);
                ReportPropertyChanging("Video");
                _Video = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Video");
                OnVideoChanged();
            }
        }
        private Nullable<global::System.Int32> _Video;
        partial void OnVideoChanging(Nullable<global::System.Int32> value);
        partial void OnVideoChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Path
        {
            get
            {
                return _Path;
            }
            set
            {
                OnPathChanging(value);
                ReportPropertyChanging("Path");
                _Path = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Path");
                OnPathChanged();
            }
        }
        private global::System.String _Path;
        partial void OnPathChanging(global::System.String value);
        partial void OnPathChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Tag
        {
            get
            {
                return _Tag;
            }
            set
            {
                OnTagChanging(value);
                ReportPropertyChanging("Tag");
                _Tag = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Tag");
                OnTagChanged();
            }
        }
        private global::System.String _Tag;
        partial void OnTagChanging(global::System.String value);
        partial void OnTagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> DiffCount
        {
            get
            {
                return _DiffCount;
            }
            set
            {
                OnDiffCountChanging(value);
                ReportPropertyChanging("DiffCount");
                _DiffCount = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("DiffCount");
                OnDiffCountChanged();
            }
        }
        private Nullable<global::System.Int32> _DiffCount;
        partial void OnDiffCountChanging(Nullable<global::System.Int32> value);
        partial void OnDiffCountChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Audio
        {
            get
            {
                return _Audio;
            }
            set
            {
                OnAudioChanging(value);
                ReportPropertyChanging("Audio");
                _Audio = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Audio");
                OnAudioChanged();
            }
        }
        private global::System.String _Audio;
        partial void OnAudioChanging(global::System.String value);
        partial void OnAudioChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Flag
        {
            get
            {
                return _Flag;
            }
            set
            {
                OnFlagChanging(value);
                ReportPropertyChanging("Flag");
                _Flag = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Flag");
                OnFlagChanged();
            }
        }
        private Nullable<global::System.Int32> _Flag;
        partial void OnFlagChanging(Nullable<global::System.Int32> value);
        partial void OnFlagChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Int32> Tid
        {
            get
            {
                return _Tid;
            }
            set
            {
                OnTidChanging(value);
                ReportPropertyChanging("Tid");
                _Tid = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("Tid");
                OnTidChanged();
            }
        }
        private Nullable<global::System.Int32> _Tid;
        partial void OnTidChanging(Nullable<global::System.Int32> value);
        partial void OnTidChanged();

        #endregion
    
    }
    
    /// <summary>
    /// 没有元数据文档可用。
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="dbModel", Name="Setting")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class Setting : EntityObject
    {
        #region 工厂方法
    
        /// <summary>
        /// 创建新的 Setting 对象。
        /// </summary>
        /// <param name="key">Key 属性的初始值。</param>
        public static Setting CreateSetting(global::System.String key)
        {
            Setting setting = new Setting();
            setting.Key = key;
            return setting;
        }

        #endregion
        #region 基元属性
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.String Key
        {
            get
            {
                return _Key;
            }
            set
            {
                if (_Key != value)
                {
                    OnKeyChanging(value);
                    ReportPropertyChanging("Key");
                    _Key = StructuralObject.SetValidValue(value, false);
                    ReportPropertyChanged("Key");
                    OnKeyChanged();
                }
            }
        }
        private global::System.String _Key;
        partial void OnKeyChanging(global::System.String value);
        partial void OnKeyChanged();
    
        /// <summary>
        /// 没有元数据文档可用。
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String Value
        {
            get
            {
                return _Value;
            }
            set
            {
                OnValueChanging(value);
                ReportPropertyChanging("Value");
                _Value = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("Value");
                OnValueChanged();
            }
        }
        private global::System.String _Value;
        partial void OnValueChanging(global::System.String value);
        partial void OnValueChanged();

        #endregion
    
    }

    #endregion
    
}
